function createfigure2(X1, Y1, S1, C1, X2, Y2, C2, X3, Y3, C3, X4, Y4, C4)
%CREATEFIGURE2(X1,Y1,S1,C1,X2,Y2,C2,X3,Y3,C3,X4,Y4,C4)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  X2:  scatter x
%  Y2:  scatter y
%  C2:  scatter c
%  X3:  scatter x
%  Y3:  scatter y
%  C3:  scatter c
%  X4:  scatter x
%  Y4:  scatter y
%  C4:  scatter c

%  Auto-generated by MATLAB on 17-Apr-2014 22:48:55

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.122277992277992 0.11 0.775 0.815]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.9 7]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.07 2.5]);
hold(axes1,'all');

% Create scatter
scatter(X1,Y1,S1,C1,'LineWidth',2,'Parent',axes1,...
    'DisplayName','Positive class');

% Create scatter
scatter(X2,Y2,S1,C2,'Marker','x','LineWidth',2,'Parent',axes1,...
    'DisplayName','Negative class');

% Create scatter
scatter(X3,Y3,S1,C3,'Marker','+','Parent',axes1);

% Create scatter
scatter(X4,Y4,S1,C4,'Marker','+','Parent',axes1);

% Create xlabel
xlabel('x_1');

% Create ylabel
ylabel('x_2');

% Create title
title('Voted Perceptron Decision Boundary Grid');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.176640926640927 0.829753521126761 0.176962676962677 0.0642605633802817]);

